name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DIRECT_URL: ${{ secrets.DIRECT_URL }}

jobs:
  lint-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: rm -f package-lock.json && npm install

      - name: Run Linter
        run: npm run lint --workspaces --if-present

      - name: Run Tests
        run: npm run test --workspaces --if-present

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information (Backend)
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_BACKEND }}

      - name: Build Project Artifacts (Backend)
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_BACKEND }}

      - name: Deploy Project Artifacts to Vercel (Backend)
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_BACKEND }}

      - name: Pull Vercel Environment Information (Frontend)
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}

      - name: Build Project Artifacts (Frontend)
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}

      - name: Deploy Project Artifacts to Vercel (Frontend)
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}

      - name: Job Summary Configuration
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "### :rocket: Deploy completed successfully!" >> $GITHUB_STEP_SUMMARY
            echo "The latest changes from \`main\` were pushed to production on Vercel." >> $GITHUB_STEP_SUMMARY
          else
            echo "### :x: Deploy Failed" >> $GITHUB_STEP_SUMMARY
            echo "Please review the detailed logs above for more information." >> $GITHUB_STEP_SUMMARY
          fi